apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
data:
  application.yml: |
    spring:
      application:
        name: spring-boot-app
      datasource:
        url: jdbc:mysql://mysql:3306/appdb
    logging:
      level:
        root: INFO