spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册到Consul的服务名
        instance-id: ${spring.application.name}:${random.value}
        service-name: ${spring.application.name}
        # 健康检查
        health-check-path: /actuator/health
        health-check-interval: 10s
        # 元数据
        metadata:
          version: 1.0.0
          zone: primary